config/routes.rb
Rails.application.routes.draw do
  root to: 'users#show'
  get 'auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout
  resources :users, only: [:index, :show, :create] do
    resources :gists, only: [:index, :show, :new, :create, :destroy]
  end
  resources :repositories, only: [:index]
  resources :commits, only: [:index]
  get '/following/commits', to: 'commits#following'
end

app/models/commit.rb
class Commit < OpenStruct

  def self.service(current_user)
    GithubService.new(current_user)
  end

  def self.all(current_user)
    commits_hash = service(current_user).recent_commits
    create_commits(commits_hash)
  end

  def self.all_following(current_user)
    commits_hash = service(current_user).following_feed
    create_commits(commits_hash)
  end

  private

  def self.create_commits(commits_hash)
    all_commits = []
    commits_hash.each do |commit_hash|
      all_commits << self.new(commit_hash)
    end
    all_commits
  end
end

app/models/gist.rb
class Gist < OpenStruct

  def self.all(current_user)
    gs = GistService.new(current_user)
    all = gs.all_gists
    gist_structs = []
    all.each do |the_gist|
      gist_structs << new(the_gist)
    end
    gist_structs
  end

  def self.find(current_user, id)
    gs = GistService.new(current_user)
    gist = gs.gist(id)
    new(gist)
  end

  def self.create_struct(current_user, params)
    hash = { description: params[:description],
             public: true,
             files: {
               params[:title] => {
                 content: params[:contents]
               }
             }}
    GistService.new(current_user).create(hash)
  end

  def name
    self.files.keys.first
  end

  def contents
    self.files[name]["content"]
  end

  def delete(current_user)
    gs = GistService.new(current_user)
    gs.destroy_gist(self)
  end

  def created_date
    Date.parse(self.created_at).strftime("%B %d, %Y")
  end
end

app/models/organization.rb
class Organization < OpenStruct

  def self.service(current_user)
    GithubService.new(current_user)
  end

  def self.all(current_user)
    all_orgs = []
    orgs_hash = service(current_user).organizations
    orgs_hash.each do |org_hash|
      all_orgs << self.new(org_hash)
    end
    all_orgs
  end
end

app/models/repository.rb
class Repository < OpenStruct

  def self.service(current_user)
    GithubService.new(current_user)
  end

  def self.all(current_user)
    all_repos = []
    repos_hash = service(current_user).repos
    repos_hash.each do |repo_hash|
      all_repos << self.new(repo_hash)
    end
    all_repos
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.token = auth["credentials"]["token"]
      user.nickname = auth["info"]["nickname"]
      user.image = auth["extra"]["raw_info"]["avatar_url"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/commits_controller.rb
class CommitsController < ApplicationController
  def index
    @commits = Commit.all(current_user)
    render json: @commits
  end

  def following
    @following_commits = Commit.all_following(current_user)
    render json: @following_commits
  end
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  def index
    @gists = Gist.all(current_user)
  end

  def show
    @gist = Gist.find(current_user, params[:id])
  end

  def create
    Gist.create_struct(current_user, params)
    redirect_to user_gists_path(current_user)
  end

  def destroy
    Gist.find(current_user, params[:id]).delete(current_user)
    redirect_to user_gists_path(current_user)
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  def index
    @repositories = Repository.all(current_user)
    render json: @repositories
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by(uid: auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if current_user
      @service = GithubService.new(current_user)
      @orgs = Organization.all(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/gists/index.html.erb
<div class="container">
  <h2>Your Gists</h2>
  <% if current_user %>
    <table class="table">
      <tr>
        <th>Title</th>
        <th>Created on</th>
      </tr>
      <% @gists.each do |the_gist| %>
        <tr>
          <td><%= link_to the_gist.name, user_gist_path(current_user, the_gist["id"]) %></td>
          <td><%= the_gist.created_date %></td>
        </tr>
      <% end %>
    </table>
    <%= link_to "Create a New Gist", new_user_gist_path(current_user)%>
  <% end %>
</div>

app/views/gists/new.html.erb
<div class="container">
  <div class="row">
    <h3>Create New Public Gist</h3>
    <div class="col-xs-4 col-xs-offset-4">
      <br/>
      <br/>
      <%= form_tag(user_gists_path) do |f| %>
        <div class="field">
          <%= label_tag :description %><br>
          <%= text_field_tag :description, nil, class:"form-control text-input", required:true %>
        </div>
        <div class="field">
          <%= label_tag :title %><br>
          <%= text_field_tag :title, nil, class:"form-control text-input", required:true %>
        </div>
        <div class="field">
          <%= label_tag :contents %><br>
          <%= text_area_tag :contents, nil, class:"form-control text-input", required:true %>
        </div>
        <br>
      <%= submit_tag "Create New Public Gist", class: "btn btn-primary"%>
      <% end %>
    </div>
  </div>
</div>
<br>

app/views/gists/show.html.erb
<div class="container">
  <h3><%= @gist.name %></h3>
  <p><%= @gist.contents %></p>
  <%= link_to "Delete this Gist", user_gist_path(current_user, @gist.id), method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ApiCurious</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: "partials/navbar" %>

<%= yield %>

</body>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</html>

app/views/partials/_commit_table.html.erb
<table class="table">
  <tr>
    <th>Repo</th>
    <th>Message</th>
  </tr>
</table>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li class="welcome-message"><%= link_to "Welcome #{current_user.name}", root_path%> </li>
        <li><%= link_to "Logout", logout_path %></li>
      <% else %>
        <li>  <%= link_to "Sign in with Github", "/auth/github" %> </li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-left">
      <% if current_user %>
        <li> <%= link_to "Gists", user_gists_path(current_user)%></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/partials/_spinning_wheel.html.erb
<%= image_tag "http://img1.targetimg1.com/tff/bm-2-tff_20160105.1/images/spinner-small.gif", class: 'spinning-wheel', id: id %>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <% if current_user %>
      <%= image_tag current_user.image %>
      <h2> <%= current_user.name %></h2>
      <p class = "grey"> <%= current_user.nickname %></p>
      <hr/>
      <div class="row followed-following">
        <div class="col-md-4">
          <h3> <%= @service.followers.count %> </h3>
          <p>followers</p>
        </div>
        <div class="col-md-4">
          <h3><%= @service.following.count %> </h3>
          <p>following</p>
        </div>
        <div class="col-md-4">
          <h3><%= @service.starred.count %></h3>
          <p>starred</p>
        </div>
      </div>
      <hr/>
      <h4>Organizations</h3>
      <% if @orgs.empty? %>
         <p class="greyer">You are not a member of any organizations</p>
      <% end %>
      <% @orgs.each do |org| %>
        <%= org.login %>
      <% end %>
    </div>
    <div class="col-md-9">
      <div class="row">
        <h4>Your Repositories</h4>
        <%= render partial: "/partials/spinning_wheel", locals: { id: "repo-wheel"} %>
        <div id="all_repos">
        </div>
        <h4 class="contributions-header">Contributions</h4>
        <div class="col-md-4 contribution-block">
          <p>Contributions in the last year</p>
          <h3 class = "contributions"><%= @service.contributions_year %></h3>
          <p>Date range</p>
        </div>
        <div class="col-md-4 contribution-block">
          <p>Longest streak</p>
          <h3 class = "contributions"><%= @service.longest_streak %></h3>
          <p>Date range</p>
        </div>
        <div class="col-md-4 contribution-block">
          <p>Current Streak</p>
          <h3 class = "contributions"> <%= @service.current_streak %> </h3>
          <p>Date range</p>
        </div>
      </div>
      <h4 class="commits-header">Contribution Activity</h4>
      <%= render partial: "/partials/spinning_wheel", locals: { id: "commits-wheel"}  %>
      <%= render partial: "/partials/commit_table" %>
      <table class="table"id="my_commits">
      </table>
      <hr>
      <h4 class="following-header">Activity from Users You Follow</h4>
      <%= render partial: "/partials/spinning_wheel", locals: { id: "following-wheel"} %>
      <%= render partial: "/partials/commit_table" %>
      <table class="table"id="following_commits">
      </table>
    <% end %>
    </div>
  </div>
</div>